pokemon_names = ["-", "Bulbasaur", "Ivysaur", "Venusaur", "Charmander", "Charmeleon", "Charizard",
			"Squirtle", "Wartortle", "Blastoise", "Caterpie", "Metapod", "Butterfree",
			"Weedle", "Kakuna", "Beedrill", "Pidgey", "Pidgeotto", "Pidgeot", "Rattata", "Raticate",
			"Spearow", "Fearow", "Ekans", "Arbok", "Pikachu", "Raichu", "Sandshrew", "Sandslash",
			"Nidoran F", "Nidorina", "Nidoqueen", "Nidoran M", "Nidorino", "Nidoking",
			"Clefairy", "Clefable", "Vulpix", "Ninetales", "Jigglypuff", "Wigglytuff",
			"Zubat", "Golbat", "Oddish", "Gloom", "Vileplume", "Paras", "Parasect", "Venonat", "Venomoth",
			"Diglett", "Dugtrio", "Meowth", "Persian", "Psyduck", "Golduck", "Mankey", "Primeape",
			"Growlithe", "Arcanine", "Poliwag", "Poliwhirl", "Poliwrath", "Abra", "Kadabra", "Alakazam",
			"Machop", "Machoke", "Machamp", "Bellsprout", "Weepinbell", "Victreebel", "Tentacool", "Tentacruel",
			"Geodude", "Graveler", "Golem", "Ponyta", "Rapidash", "Slowpoke", "Slowbro",
			"Magnemite", "Magneton", "Farfetch'd", "Doduo", "Dodrio", "Seel", "Dewgong", "Grimer", "Muk",
			"Shellder", "Cloyster", "Gastly", "Haunter", "Gengar", "Onix", "Drowzee", "Hypno",
			"Krabby", "Kingler", "Voltorb", "Electrode", "Exeggcute", "Exeggutor", "Cubone", "Marowak",
			"Hitmonlee", "Hitmonchan", "Lickitung", "Koffing", "Weezing", "Rhyhorn", "Rhydon", "Chansey",
			"Tangela", "Kangaskhan", "Horsea", "Seadra", "Goldeen", "Seaking", "Staryu", "Starmie",
			"Mr. Mime", "Scyther", "Jynx", "Electabuzz", "Magmar", "Pinsir", "Tauros", "Magikarp", "Gyarados",
			"Lapras", "Ditto", "Eevee", "Vaporeon", "Jolteon", "Flareon", "Porygon", "Omanyte", "Omastar",
			"Kabuto", "Kabutops", "Aerodactyl", "Snorlax", "Articuno", "Zapdos", "Moltres",
			"Dratini", "Dragonair", "Dragonite", "Mewtwo", "Mew",
			"Chikorita", "Bayleef", "Meganium", "Cyndaquil", "Quilava", "Typhlosion",
			"Totodile", "Croconaw", "Feraligatr", "Sentret", "Furret", "Hoothoot", "Noctowl",
			"Ledyba", "Ledian", "Spinarak", "Ariados", "Crobat", "Chinchou", "Lanturn", "Pichu", "Cleffa",
			"Igglybuff", "Togepi", "Togetic", "Natu", "Xatu", "Mareep", "Flaaffy", "Ampharos", "Bellossom",
			"Marill", "Azumarill", "Sudowoodo", "Politoed", "Hoppip", "Skiploom", "Jumpluff", "Aipom",
			"Sunkern", "Sunflora", "Yanma", "Wooper", "Quagsire", "Espeon", "Umbreon", "Murkrow", "Slowking",
			"Misdreavus", "Unown", "Wobbuffet", "Girafarig", "Pineco", "Forretress", "Dunsparce", "Gligar",
			"Steelix", "Snubbull", "Granbull", "Qwilfish", "Scizor", "Shuckle", "Heracross", "Sneasel",
			"Teddiursa", "Ursaring", "Slugma", "Magcargo", "Swinub", "Piloswine", "Corsola", "Remoraid", "Octillery",
			"Delibird", "Mantine", "Skarmory", "Houndour", "Houndoom", "Kingdra", "Phanpy", "Donphan",
			"Porygon2", "Stantler", "Smeargle", "Tyrogue", "Hitmontop", "Smoochum", "Elekid", "Magby", "Miltank",
			"Blissey", "Raikou", "Entei", "Suicune", "Larvitar", "Pupitar", "Tyranitar", "Lugia", "Ho-Oh", "Celebi",
			"Treecko", "Grovyle", "Sceptile", "Torchic", "Combusken", "Blaziken", "Mudkip", "Marshtomp",
			"Swampert", "Poochyena", "Mightyena", "Zigzagoon", "Linoone", "Wurmple", "Silcoon", "Beautifly",
			"Cascoon", "Dustox", "Lotad", "Lombre", "Ludicolo", "Seedot", "Nuzleaf", "Shiftry",
			"Taillow", "Swellow", "Wingull", "Pelipper", "Ralts", "Kirlia", "Gardevoir", "Surskit",
			"Masquerain", "Shroomish", "Breloom", "Slakoth", "Vigoroth", "Slaking", "Nincada", "Ninjask",
			"Shedinja", "Whismur", "Loudred", "Exploud", "Makuhita", "Hariyama", "Azurill", "Nosepass",
			"Skitty", "Delcatty", "Sableye", "Mawile", "Aron", "Lairon", "Aggron", "Meditite", "Medicham",
			"Electrike", "Manectric", "Plusle", "Minun", "Volbeat", "Illumise", "Roselia", "Gulpin",
			"Swalot", "Carvanha", "Sharpedo", "Wailmer", "Wailord", "Numel", "Camerupt", "Torkoal",
			"Spoink", "Grumpig", "Spinda", "Trapinch", "Vibrava", "Flygon", "Cacnea", "Cacturne", "Swablu",
			"Altaria", "Zangoose", "Seviper", "Lunatone", "Solrock", "Barboach", "Whiscash", "Corphish",
			"Crawdaunt", "Baltoy", "Claydol", "Lileep", "Cradily", "Anorith", "Armaldo", "Feebas",
			"Milotic", "Castform", "Kecleon", "Shuppet", "Banette", "Duskull", "Dusclops", "Tropius",
			"Chimecho", "Absol", "Wynaut", "Snorunt", "Glalie", "Spheal", "Sealeo", "Walrein", "Clamperl",
			"Huntail", "Gorebyss", "Relicanth", "Luvdisc", "Bagon", "Shelgon", "Salamence", "Beldum",
			"Metang", "Metagross", "Regirock", "Regice", "Registeel", "Latias", "Latios", "Kyogre",
			"Groudon", "Rayquaza", "Jirachi", "Deoxys",
			"Turtwig", "Grotle", "Torterra", "Chimchar", "Monferno", "Infernape", "Piplup", "Prinplup",
			"Empoleon", "Starly", "Staravia", "Staraptor", "Bidoof", "Bibarel", "Kricketot", "Kricketune",
			"Shinx", "Luxio", "Luxray", "Budew", "Roserade", "Cranidos", "Rampardos", "Shieldon", "Bastiodon",
			"Burmy", "Wormadam", "Mothim", "Combee", "Vespiquen", "Pachirisu", "Buizel", "Floatzel", "Cherubi",
			"Cherrim", "Shellos", "Gastrodon", "Ambipom", "Drifloon", "Drifblim", "Buneary", "Lopunny",
			"Mismagius", "Honchkrow", "Glameow", "Purugly", "Chingling", "Stunky", "Skuntank", "Bronzor",
			"Bronzong", "Bonsly", "Mime Jr.", "Happiny", "Chatot", "Spiritomb", "Gible", "Gabite", "Garchomp",
			"Munchlax", "Riolu", "Lucario", "Hippopotas", "Hippowdon", "Skorupi", "Drapion", "Croagunk",
			"Toxicroak", "Carnivine", "Finneon", "Lumineon", "Mantyke", "Snover", "Abomasnow", "Weavile",
			"Magnezone", "Lickilicky", "Rhyperior", "Tangrowth", "Electivire", "Magmortar", "Togekiss",
			"Yanmega", "Leafeon", "Glaceon", "Gliscor", "Mamoswine", "Porygon-Z", "Gallade", "Probopass",
			"Dusknoir", "Froslass", "Rotom", "Uxie", "Mesprit", "Azelf", "Dialga", "Palkia", "Heatran",
			"Regigigas", "Giratina", "Cresselia", "Phione", "Manaphy", "Darkrai", "Shaymin", "Arceus"
]

zones = [
    "Jubilife City","Jubilife City","Jubilife City","Jubilife City","Jubilife City","Jubilife City","Jubilife City",
    "Jubilife City","Jubilife City","Jubilife City","Jubilife City","Jubilife City","Jubilife City","Jubilife City",
    "Jubilife City","Jubilife City","Jubilife City","Jubilife City","Jubilife City","Jubilife City","Jubilife City",
    "Jubilife City","Jubilife City","Jubilife City","Canalave City","Canalave City","Canalave Gym","Canalave City",
    "Canalave City","Canalave City","Canalave City","Canalave City","Canalave City","Canalave City","Canalave City",
    "Canalave City","Canalave City","Canalave City","Oreburgh City","Oreburgh City","Oreburgh Gym","Oreburgh City",
    "Oreburgh City","Oreburgh City","Oreburgh City","Oreburgh City","Oreburgh City","Oreburgh City","Oreburgh City",
    "Oreburgh City","Oreburgh City","Oreburgh City","Oreburgh City","Oreburgh City","Eterna City","Eterna City",
    "Eterna Gym","Eterna Gym","Eterna City","Eterna City","Eterna City","Eterna City","Eterna City","Eterna City",
    "Eterna City","Eterna City","Eterna City","Eterna City","Eterna City","Eterna City","Eterna City","Eterna City",
    "Eterna City","Eterna City","Hearthome City","Hearthome City","Hearthome Gym","Hearthome Gym","Hearthome Gym",
    "Hearthome Gym","Hearthome Gym","Hearthome Gym","Hearthome Gym","Hearthome Gym","Hearthome Gym","Hearthome Gym",
    "Hearthome Gym","Hearthome Gym","Hearthome Gym","Hearthome City","Hearthome City","Hearthome City","Hearthome City",
    "Hearthome City","Hearthome City","Hearthome City","Hearthome City","Hearthome City","Hearthome City","Hearthome City",
    "Hearthome City","Hearthome City","Hearthome City","Hearthome City","Hearthome City","Hearthome City","Hearthome City",
    "Hearthome City","Hearthome City","Hearthome City","Pastoria City","Pastoria City","Pastoria Gym","Pastoria City",
    "Pastoria City","Pastoria City","Pastoria City","Pastoria City","Pastoria City","Pastoria City","Pastoria City",
    "Pastoria City","Pastoria City","Veilstone City","Veilstone Gym","Veilstone City","Veilstone City","Veilstone City",
    "Veilstone City","Veilstone City","Veilstone City","Veilstone City","Veilstone City","Veilstone City","Veilstone City",
    "Veilstone City","Veilstone City","Veilstone City","Veilstone City","Veilstone City","Veilstone City","Veilstone City",
    "Sunyshore City","Sunyshore City","Sunyshore Gym","Sunyshore Gym","Sunyshore Gym","Sunyshore City","Sunyshore City",
    "Sunyshore City","Sunyshore City","Sunyshore City","Sunyshore City","Sunyshore City","Sunyshore City","Sunyshore City",
    "Sunyshore City","Sunyshore City","Sunyshore City","Snowpoint City","Snowpoint City","Snowpoint Gym","Snowpoint City",
    "Snowpoint City","Snowpoint City","Snowpoint City","Snowpoint City","Pokémon League","Pokémon League","Pokémon League",
    "Pokémon League","Pokémon League","Pokémon League","Pokémon League","Pokémon League","Pokémon League","Pokémon League",
    "Pokémon League","Pokémon League","Pokémon League","Pokémon League","Pokémon League","Pokémon League","Pokémon League",
    "Pokémon League","Pokémon League","Fight Area","Fight Area","Fight Area","Fight Area","Fight Area","Fight Area",
    "Fight Area","Fight Area","Fight Area","Oreburgh Mine","Oreburgh Mine","Valley Windworks","Valley Windworks",
    "Eterna Forest","Eterna Forest","Fuego Ironworks","Fuego Ironworks","Mount Coronet","Mount Coronet","Mount Coronet",
    "Mount Coronet","Mount Coronet","Mount Coronet","Mount Coronet","Mount Coronet","Mount Coronet","Mount Coronet",
    "Mount Coronet","Mount Coronet","Mount Coronet","Spear Pillar","Spear Pillar","Hall of Origin","Great Marsh",
    "Great Marsh","Great Marsh","Great Marsh","Great Marsh","Great Marsh","Solaceon Ruins","Solaceon Ruins","Solaceon Ruins",
    "Solaceon Ruins","Solaceon Ruins","Solaceon Ruins","Solaceon Ruins","Solaceon Ruins","Solaceon Ruins","Solaceon Ruins",
    "Solaceon Ruins","Solaceon Ruins","Solaceon Ruins","Solaceon Ruins","Solaceon Ruins","Solaceon Ruins","Solaceon Ruins",
    "Solaceon Ruins","Solaceon Ruins","Victory Road","Victory Road","Victory Road","Victory Road","Victory Road",
    "Victory Road","Ramanas Park","Amity Square","Ravaged Path","Floaroma Meadow","Floaroma Meadow","Oreburgh Gate",
    "Oreburgh Gate","Fullmoon Island","Fullmoon Island","Stark Mountain","Stark Mountain","Stark Mountain","Stark Mountain",
    "Sendoff Spring","Turnback Cave","Turnback Cave","Turnback Cave","Turnback Cave","Turnback Cave","Turnback Cave",
    "Turnback Cave","Turnback Cave","Turnback Cave","Turnback Cave","Turnback Cave","Turnback Cave","Turnback Cave",
    "Turnback Cave","Turnback Cave","Turnback Cave","Turnback Cave","Turnback Cave","Turnback Cave","Turnback Cave",
    "Turnback Cave","Flower Paradise","Snowpoint Temple","Snowpoint Temple","Snowpoint Temple","Snowpoint Temple",
    "Snowpoint Temple","Snowpoint Temple","Wayward Cave","Wayward Cave","Ruin Maniac Cave","Ruin Maniac Cave",
    "Maniac Tunnel","Trophy Garden","Iron Island","Iron Island","Iron Island","Iron Island","Iron Island","Iron Island",
    "Iron Island","Iron Island","Old Chateau","Old Chateau","Old Chateau","Old Chateau","Old Chateau","Old Chateau",
    "Old Chateau","Old Chateau","Old Chateau","Galactic HQ","Galactic HQ","Galactic HQ","Galactic HQ","Galactic HQ",
    "Galactic HQ","Galactic HQ","Galactic HQ","Lake Verity","Lake Verity","Lake Verity","Lake Valor","Lake Valor",
    "Lake Valor","Lake Acuity","Lake Acuity","Lake Acuity","Newmoon Island","Newmoon Island","Battle Park","Battle Park",
    "Battle Park","Battle Park","Battle Park","Battle Tower","Battle Tower","Battle Tower","Battle Tower","Battle Tower",
    "Battle Tower","Mystery Zone","Verity Lakefront","Valor Lakefront","Valor Lakefront","Valor Lakefront","Valor Lakefront",
    "Acuity Lakefront","Spring Path","Mystery Zone","Route 201","Route 202","Route 203","Route 204","Route 204","Route 205",
    "Route 205","Route 205","Route 206","Route 206","Route 207","Route 208","Route 208","Route 209","Route 209","Route 209",
    "Route 209","Route 209","Route 209","Route 210","Route 210","Route 210","Route 210","Route 211","Route 211","Route 212",
    "Route 212","Route 212","Route 212","Route 212","Route 212","Route 213","Route 213","Route 213","Route 213","Route 213",
    "Route 213","Route 213","Route 214","Route 214","Route 215","Route 216","Route 216","Route 217","Route 217","Route 217",
    "Route 218","Route 218","Route 218","Route 219","Route 221","Route 221","Route 221","Route 222","Route 222","Route 222",
    "Route 222","Route 224","Route 225","Route 225","Route 227","Route 227","Route 228","Route 228","Route 228","Route 228",
    "Route 229","Mystery Zone","Twinleaf Town","Twinleaf Town","Twinleaf Town","Twinleaf Town","Twinleaf Town",
    "Twinleaf Town","Twinleaf Town","Sandgem Town","Sandgem Town","Sandgem Town","Sandgem Town","Sandgem Town",
    "Sandgem Town","Sandgem Town","Sandgem Town","Sandgem Town","Floaroma Town","Floaroma Town","Floaroma Town",
    "Floaroma Town","Floaroma Town","Floaroma Town","Floaroma Town","Floaroma Town","Solaceon Town","Solaceon Town",
    "Solaceon Town","Solaceon Town","Solaceon Town","Solaceon Town","Solaceon Town","Solaceon Town","Solaceon Town",
    "Solaceon Town","Celestic Town","Celestic Town","Celestic Town","Celestic Town","Celestic Town","Celestic Town",
    "Celestic Town","Celestic Town","Celestic Town","Survival Area","Survival Area","Survival Area","Survival Area",
    "Survival Area","Survival Area","Survival Area","Survival Area","Resort Area","Resort Area","Resort Area",
    "Resort Area","Resort Area","Resort Area","Resort Area","Resort Area","Resort Area","Resort Area","Mystery Zone",
    "Mystery Zone","Route 220","Route 223","Route 226","Route 226","Route 230","Seabreak Path","Mystery Zone",
    "Mystery Zone","Mystery Zone","Eterna City","Ramanas Park","Ramanas Park","Ramanas Park","Ramanas Park","Ramanas Park",
    "Ramanas Park","Ramanas Park","Ramanas Park","Ramanas Park","Ramanas Park","Ramanas Park","Ramanas Park","Ramanas Park",
    "Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground",
    "Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground",
    "Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground",
    "Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground",
    "Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground",
    "Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground",
    "Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground",
    "Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground",
    "Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground",
    "Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground",
    "Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground",
    "Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground",
    "Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground",
    "Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground",
    "Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground",
    "Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground",
    "Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground",
    "Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground",
    "Grand Underground","Grand Underground","Grand Underground","Ramanas Park","Grand Underground","Grand Underground",
    "Grand Underground","Grand Underground","Ramanas Park","Ramanas Park","Jubilife City","Grand Underground",
    "Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground",
    "Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground",
    "Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground","Grand Underground",
    "Grand Underground","Grand Underground"
]

sinnoh_pokemon = [
    "Turtwig","Grotle","Torterra","Chimchar","Monferno","Infernape","Piplup","Prinplup","Empoleon","Starly","Staravia",
    "Staraptor","Bidoof","Bibarel","Kricketot","Kricketune","Shinx","Luxio","Luxray","Abra","Kadabra","Alakazam","Magikarp",
    "Gyarados","Budew","Roselia","Roserade","Zubat","Golbat","Crobat","Geodude","Graveler","Golem","Onix","Steelix",
    "Cranidos","Rampardos","Shieldon","Bastiodon","Machop","Machoke","Machamp","Psyduck","Golduck","Burmy","Wormadam",
    "Mothim","Wurmple","Silcoon","Beautifly","Cascoon","Dustox","Combee","Vespiquen","Pachirisu","Buizel","Floatzel",
    "Cherubi","Cherrim","Shellos","Gastrodon","Heracross","Aipom","Ambipom","Drifloon","Drifblim","Buneary","Lopunny",
    "Gastly","Haunter","Gengar","Misdreavus","Mismagius","Murkrow","Honchkrow","Glameow","Purugly","Goldeen","Seaking",
    "Barboach","Whiscash","Chingling","Chimecho","Stunky","Skuntank","Meditite","Medicham","Bronzor","Bronzong","Ponyta",
    "Rapidash","Bonsly","Sudowoodo","Mime Jr.","Mr. Mime","Happiny","Chansey","Blissey","Cleffa","Clefairy","Clefable",
    "Chatot","Pichu","Pikachu","Raichu","Hoothoot","Noctowl","Spiritomb","Gible","Gabite","Garchomp","Munchlax","Snorlax",
    "Unown","Riolu","Lucario","Wooper","Quagsire","Wingull","Pelipper","Girafarig","Hippopotas","Hippowdon","Azurill",
    "Marill","Azumarill","Skorupi","Drapion","Croagunk","Toxicroak","Carnivine","Remoraid","Octillery","Finneon","Lumineon",
    "Tentacool","Tentacruel","Feebas","Milotic","Mantyke","Mantine","Snover","Abomasnow","Sneasel","Weavile","Uxie",
    "Mesprit","Azelf","Dialga","Palkia","Manaphy"
]